//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDEApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VDEApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1761811996142&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;1592&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M512 64c247.424 0 448 200.576 448 448s-200.576 448-448 448S64 759.424 64 512 264.576 64 512 64z m0 85.333333C311.701333 149.333333 149.333333 311.701333 149.333333 512s162.368 362.666667 362.666667 362.666667 362.666667-162.368 362.666667-362.666667S712.298667 149.333333 512 149.333333z m21.333333 277.333334a21.333333 21.333333 0 0 1 21.333334 21.333333v2 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_about {
            get {
                return ResourceManager.GetString("icon_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1761615075053&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1079 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;10118&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;path d=&quot;M43.464798 294.571526l86.302701-81.844773 51.823413 48.758588-86.372355 82.262703 51.753758 48.758588L233.275015 310.66186l51.753759 48.758588-86.302701 81.844772 17.831712 42.628937 269.07775-269.07775L302.303245 16.368954a89.785457 89.785457 0 0 0-112.632338 8.637236L17.065506 188.695735a59.555132 59.555132 0 0 0 9.055166 90.551663z m-17.274471 675.30644 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_calibration {
            get {
                return ResourceManager.GetString("icon_calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1761615541530&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;12492&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;path d=&quot;M145.1 212.8h96.1V248h-96.1z&quot; fill=&quot;#333333&quot; p-id=&quot;12493&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M863.6 277H745.9c-12 0-23.2-6-29.8-16l-50.4-75.6c-6.6-10-17.8-16-29.8-16H387.8c-12 0-23.2 6-29.8 16L307.7 261c-6.6 10-17.8 16-29.8 16H160.4c-53.1 0-96.1 43.1-96.1 96.1v385.3c0 53.1 43.1 96.1 96.1 96.1h703.2c53.1 0 96.1-43.1 96.1-96.1V373.1c0-53-43-96.1-96.1-96.1zM512 783.7c-113.5 0-2 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_camera {
            get {
                return ResourceManager.GetString("icon_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1761613786294&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;11438&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;path d=&quot;M711.68 392.704v68.388571h20.918857c18.432 0 29.549714-3.730286 35.84-9.142857 5.851429-4.900571 9.654857-12.946286 9.654857-27.355428 0-13.897143-3.949714-20.406857-9.508571-24.356572-6.729143-4.754286-18.432-7.533714-37.302857-7.533714H711.68z&quot; p-id=&quot;11439&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M146.285714 109.714286a73.142857 73.142857 0 0 0-73.142857 73.142857V731.428571c0  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_communication {
            get {
                return ResourceManager.GetString("icon_communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1761613529861&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;4423&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;path d=&quot;M939 177.5c-8.6-12.7-19.6-23.6-32.4-32.4-6.3-4.3-13.1-8-20.3-11-14.3-6.1-30-9.4-46.3-9.4H183.9c-16.5 0-32.1 3.3-46.3 9.4-7.2 3-14 6.7-20.3 11-12.7 8.6-23.6 19.6-32.4 32.4-12.9 19.1-20.4 42-20.4 66.5v417.5c0 65.6 53.6 119.3 119.3 119.3h656.1c65.6 0 119.3-53.6 119.3-119.3V244.1c0.1-24.5-7.4-47.5-20.2-66.6zM810.2 542.3H671.6c-7.7 0-15.2-3-20.7-8.4L488.5 378.1  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_inspection {
            get {
                return ResourceManager.GetString("icon_inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;256&quot; height=&quot;256&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;path fill=&quot;currentColor&quot; d=&quot;M3 23q-.825 0-1.412-.587T1 21V3q0-.825.588-1.412T3 1h18q.825 0 1.413.588T23 3v18q0 .825-.587 1.413T21 23zm3.85-4H17q.825 0 1.413-.587T19 17v-3q0-.425-.288-.712T18 13t-.712.288T17 14v3H6.85l.85-.85q.3-.3.288-.7t-.288-.7q-.3-.3-.712-.312t-.713.287L3.7 17.3q-.15.15-.213.325T3.426 18t.063.375t.212.325l2.575 2.575q.3.3.713.288t.712-.313q.275-.3.288-.7t-.288-.7zm10.3-12l-.85.85q-.3.3-.288.7t.288.7q.3. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_looprun {
            get {
                return ResourceManager.GetString("icon_looprun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;256&quot; height=&quot;256&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;path fill=&quot;currentColor&quot; d=&quot;M3 23q-.825 0-1.412-.587T1 21V3q0-.825.588-1.412T3 1h18q.825 0 1.413.588T23 3v18q0 .825-.587 1.413T21 23zm3.85-4H17q.825 0 1.413-.587T19 17v-3q0-.425-.288-.712T18 13t-.712.288T17 14v3H6.85l.85-.85q.3-.3.288-.7t-.288-.7q-.3-.3-.712-.312t-.713.287L3.7 17.3q-.15.15-.213.325T3.426 18t.063.375t.212.325l2.575 2.575q.3.3.713.288t.712-.313q.275-.3.288-.7t-.288-.7zm10.3-12l-.85.85q-.3.3-.288.7t.288.7q.3. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_onece {
            get {
                return ResourceManager.GetString("icon_onece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1761614179384&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;1678&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;path d=&quot;M514 114.3c-219.9 0-398.9 178.9-398.9 398.8 0.1 220 179 398.9 398.9 398.9 219.9 0 398.8-178.9 398.8-398.9 0-219.8-178.9-398.8-398.8-398.8z m-35.6 531.5c0 32.5-26.3 58.8-58.8 58.8s-58.8-26.3-58.8-58.8V381.4c0-32.5 26.3-58.8 58.8-58.8s58.8 26.3 58.8 58.8v264.4z m188.7 0c0 32.5-26.3 58.8-58.8 58.8s-58.8-26.3-58.8-58.8V381.4c0-32.5 26.3-58.8 58.8-58.8s58.8 26.3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_pause {
            get {
                return ResourceManager.GetString("icon_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1761614147685&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;1513&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;path d=&quot;M514 114.3c-219.9 0-398.9 178.9-398.9 398.9 0.1 219.9 179 398.8 398.9 398.8 219.9 0 398.8-178.9 398.8-398.8S733.9 114.3 514 114.3z m173 421.9L437.1 680.5c-17.7 10.2-39.8-2.6-39.8-23V368.9c0-20.4 22.1-33.2 39.8-23L687 490.2c17.7 10.2 17.7 35.8 0 46z&quot; fill=&quot;#0C0C0C&quot; p-id=&quot;1514&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string icon_play {
            get {
                return ResourceManager.GetString("icon_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1761616500780&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;13881&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;path d=&quot;M884.8 1014.4H144c-36.8 0-67.2-30.4-67.2-67.2V209.6c0-36.8 30.4-67.2 67.2-67.2h33.6v100.8c0 36.8 30.4 67.2 67.2 67.2h538.4c36.8 0 67.2-30.4 67.2-67.2V142.4H884c36.8 0 67.2 30.4 67.2 67.2v737.6c0.8 36.8-29.6 67.2-66.4 67.2z m-150.4-456c-20-19.2-52-19.2-72 0l-180 171.2-84-80c-20-19.2-52-19.2-72 0s-20 49.6 0 68l120 113.6c20 19.2 52 19.2 72 0l216-204.8c20-18.4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_projectmanager {
            get {
                return ResourceManager.GetString("icon_projectmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1761616855009&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;26027&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;path d=&quot;M783.317333 154.389333l0.106667 0.32 0.064 0.149334 0.021333 0.106666 0.746667 2.410667a42.453333 42.453333 0 0 1 1.344 8.938667l0.021333 0.853333v0.853333a42.368 42.368 0 0 1-6.208 22.314667 42.88 42.88 0 0 1-2.261333 3.349333l-0.576 0.746667-0.576 0.725333a42.581333 42.581333 0 0 1-2.517333 2.837334l-0.64 0.64-0.661334 0.64a42.304 42.304 0 0 1-6.101333 4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_replayimage {
            get {
                return ResourceManager.GetString("icon_replayimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg t=&quot;1762247402574&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;5856&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;path d=&quot;M883.2 247.488c-17.088-17.088-44.8-17.088-59.712 0L409.6 665.6 200.512 460.8c-17.024-17.088-44.8-17.088-59.712 0-17.088 17.088-17.088 44.8 0 59.712L379.712 755.2c8.576 8.512 19.2 12.8 29.888 12.8a42.112 42.112 0 0 0 29.888-12.8l443.712-448a41.216 41.216 0 0 0 0-59.712z&quot; p-id=&quot;5857&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string icon_true {
            get {
                return ResourceManager.GetString("icon_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
